scooter:
  shop:
    timezone: 'Europe/Moscow'
    jodaDateTimeFormat: 'yyyy-MM-dd HH:mm:ss'
    chargeDegradationAtSecondUnit: 0.0833333333333333333333

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG
        SQL: DEBUG
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG

server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /

spring:
#  devtools:
#    restart:
#      enabled: true
#    livereload:
#      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.5.3:5432/scooter_shop
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#   defer-datasource-initialization: true
#    sql:
#      init:
#        mode: always
#        platform: postgresql
  mvc:
    hiddenmethod:
      filter:
        enabled: true


