version: '2'

networks:
  opc-ua-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.10.15.0/24"

services:
  asneg-demo:
    container_name: asneg-demo${BUILD_TAG}
    hostname: asneg-demo
    restart: always
    image: asneg/asneg-demo:release-4
    expose:
      - "8889"
      - "4840"
    volumes:
      - demo_server_pki:/etc/OpcUaStack/ASNeG-Demo/pki
    networks:
      opc-ua-network:
        ipv4_address: 172.10.15.10

  webserver:
    container_name: webserver${BUILD_TAG}
    hostname: webserver
    restart: always
    depends_on:
      - asneg-demo
    expose:
      - "8080"
      - "8081"
      - "8082"
      - "22"
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - SSH_AUTH_SOCK=/ssh-agent
    build:
      context: ../OpcUaWebServer
      dockerfile: ./OpcUaWebServer.Dockerfile
    volumes:
      - web_server_pki:/etc/OpcUaStack/OpcUaWebServer/pki
      - .:/code
    #command: >-
    #  bash -c "sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClient0.xml
    #  && sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClient1.xml.temporal
    #  && sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClientTest.xml.temporal
    #  && OpcUaServer4 /etc/OpcUaStack/OpcUaWebServer/OpcUaServer.xml"
    command: >-
      bash -c "sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClient.xml
      && OpcUaServer4 /etc/OpcUaStack/OpcUaWebServer/OpcUaServer.xml"
    networks:
      opc-ua-network:
        ipv4_address: 172.10.15.11

  test_client:
    container_name: test_client${BUILD_TAG}
    build:
      context: ../OpcUaWebServer
      dockerfile: ./OpcUaWebServer.Dockerfile
    depends_on:
      - asneg-demo
      - webserver
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - WSS_GATEWAY_URL=wss://172.10.15.11:8082
      - WS_GATEWAY_URL=ws://172.10.15.11:8082
      - WSS_SERVER_URL=wss://172.10.15.11:8081
      - WS_SERVER_URL=ws://172.10.15.11:8081
      - OPC_SERVER_URL=opc.tcp://172.10.15.11:8889
      - DOCKER_ENABLE=YES
    command: echo "Test client is ready"
    volumes:
      - web_server_pki:/tmp/etc/OpcUaStack/OpcUaWebServer/pki
      - demo_server_pki:/tmp/etc/OpcUaStack/ASNeG-Demo/pki
      - .:/code
    networks:
      opc-ua-network:
        ipv4_address: 172.10.15.12

  #spring-opc-ua-client:
  #  container_name: spring-opc-ua-client${BUILD_TAG}
  #  build:
  #    context: .
  #    dockerfile: ./OpcUaSpringClient.Dockerfile
  #  depends_on:
  #   - asneg_demo
  #   - webserver
  # environment:
  #   - xml-filepath: "/home/dev/projects/java/spring-prof-souz-opc-ua-client/template.xml"
  #   - wss-host: 192.168.0.11
  #   - wss-port: 8081
  # networks:
  #  opc-ua-network:
  #     ipv4_address: 172.10.15.13

volumes:
  demo_server_pki:
  web_server_pki:



